require('dotenv').config();
const express = require('express');
const cors = require('cors');
const cron = require('node-cron');
const { requireAuth } = require('./middleware/auth');
const channelRoutes = require('./routes/channels');
const videoRoutes = require('./routes/videos');
const refreshRoutes = require('./routes/refresh');
const settingsRoutes = require('./routes/settings');
const youtubeDownloadRoute = require('./routes/youtube-download');
const cobaltDownloadRoute = require('./routes/cobalt-download');
const { downloadRateLimiter } = require('./middleware/downloadRateLimiter');
const { collectAll, collectYouTube, collectTikTok } = require('./cron/collector');
const { discoverNewVideos } = require('./cron/videoDiscovery');

const app = express();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors());
app.use(express.json());

// Root route
app.get('/', (req, res) => {
  res.status(200).send('API działa git!');
});

// Health check — public (no auth)
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// SSE progress endpoint — public (no auth)
// EventSource browser API can't send custom headers, so this is unauthenticated.
// jobId is a random UUID generated by the client, only the client that started
// the download knows it; no sensitive data is exposed (just progress %).
const { progressSseRouter } = require('./routes/youtube-download');
app.use('/api/tools', progressSseRouter);

// Auth middleware for all /api/* routes (except /api/health and /api/tools/youtube-progress above)
app.use('/api', requireAuth);

// Routes
app.use('/api/channels', channelRoutes);
app.use('/api/channels', videoRoutes);
app.use('/api', refreshRoutes);
app.use('/api', settingsRoutes);
app.use('/api/tools', requireAuth, downloadRateLimiter, youtubeDownloadRoute);
app.use('/api/tools', requireAuth, downloadRateLimiter, cobaltDownloadRoute);

// Schedule YouTube collection every hour (0 * * * *)
cron.schedule('0 * * * *', () => {
  console.log(`[cron] Hourly YouTube collection triggered at ${new Date().toISOString()}`);
  collectYouTube();
});

// Schedule TikTok collection every 6 hours (0 */6 * * *)
cron.schedule('0 */6 * * *', () => {
  console.log(`[cron] 6-hourly TikTok collection triggered at ${new Date().toISOString()}`);
  collectTikTok();
});

// Schedule new video discovery every 5 minutes (*/5 * * * *)
cron.schedule('*/5 * * * *', () => {
  console.log(`[cron] 5-min video discovery triggered at ${new Date().toISOString()}`);
  discoverNewVideos();
});

// Delayed initial collection — wait 5s for frontend to sync API keys via POST /api/settings
setTimeout(() => {
  console.log('[cron] Running initial collection (after 5s delay for key sync)...');
  collectAll();
}, 5000);

// Start server
app.listen(PORT, () => {
  console.log(`[server] Backend running on http://localhost:${PORT}`);
});
